R3SOL-368 Downgrade jackson to 2.17.2 (#1700)
Upgrading Jackson from 2.17.2 to 2.18.0 (see fb818fe) in Corda API has broken some of the Ledger Tests.

Causing the tests to fail with:

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `net.corda.v5.ledger.common.transaction.CordaPackageSummary` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 604] (through reference chain: net.corda.ledger.common.data.transaction.TransactionMetadataImpl["cpkMetadata"]->java.util.ArrayList[0])

It looks like Jackson is trying to construct CordaPackageSummary (which is an interface) when deserialising instead of CordaPackageSummaryImpl.